workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    environment:
      groups:
        - codemagic
      vars:
        GRADLE_BUILD_FILE: app/build.gradle
        PACKAGE_NAME: com.audioplayer
      android_signing:
        - codemagic-android-default
    scripts:
      - name: Check environment variables
        script: |
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cat local.properties
      - name: Check project structure
        script: |
          ls -la
          ls -la app/
      - name: Build with Gradle wrapper
        script: |
          # Use bash to run the script to avoid shell compatibility issues
          bash ./gradlew clean assembleDebug --info
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
