workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    environment:
      groups:
        - codemagic
      vars:
        GRADLE_BUILD_FILE: app/build.gradle
        PACKAGE_NAME: com.audioplayer
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Set execute permission for gradlew
        script: |
          chmod +x ./gradlew
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build Android app
        script: |
          ./gradlew assembleDebug --info
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
